/* Copyright IBM Corp. 2017  All Rights Reserved.                    */

module.exports = {
  ID_MIN_LENGTH: 1,
  ID_MAX_LENGTH: 64,
  NAME_MIN_LENGTH: 1,
  NAME_MAX_LENGTH: 256,
  TYPE_MIN_LENGTH: 1,
  TYPE_MAX_LENGTH: 36,
  URL_MIN_LENGTH: 1,
  URL_MAX_LENGTH: 2048,
  POSITION: {
    TAIL: 'NIL',
  },
  IF_MODIFIED_SINCE: 'if-modified-since',
  LAST_MODIFIED: 'last-modified',
  ETAG_HEADER: 'etag',
  IF_NONE_MATCH: 'if-none-match',
  CACHE_CONTROL: 'cache-control',
  TAGS_MAX_LENGTH: 4096,
  METADATA_MAX_LENGTH: 4096,
  DATASYNC_MIN_TTL_HOURS: 2,
  DATASYNC_MAX_TTL_HOURS: 720,
  EVENTS: {
    COMMUNITY_UPDATED: 'community.updated',
    COMMUNITY_DELETED: 'community.softdeleted',
    COMMUNITY_RESTORED: 'community.restored',
    COMMUNITY_NOTIFY_MEMBER_ADD: 'communities.notification.memberadd',
    COMMUNITY_MEMBERSHIP_ADDED: 'community.membership.added',
    COMMUNITY_NOTIFY_MEMBER_REMOVE: 'communities.notification.memberremove',
    COMMUNITY_MEMBERSHIP_REMOVE: 'community.membership.removed',
  },
  STATE: {
    DELETED: 'DELETED',
    NOACCESS: 'NOACCESS',
    NORMAL: 'NORMAL',
    INACTIVE: 'INACTIVE',
    ACTIVE: 'ACTIVE',
  },
  ENTRY_TYPE: {
    COMMUNITY: 'community',
    PEOPLE: 'people',
  },
  DEFAULT_PAGE_SIZE: 10,
  MAXIMUM_PAGE_SIZE: 100,
  CONNECTIONS_EVENTS_CHANNEL: 'connections.events',
  CONNECTIONS_EVENTS_SUBSCRIPTIONS_HASH: 'connections.events.subscriptions',
  CONNECTIONS_EVENTS_SUBSCRIPTIONS_REG_NAME: 'itm',
  CONNECTIONS_EVENTS_SUBSCRIPTION_LIST: 'connections.events.itm',
  REDIS_BRPOP_TIMEOUT: 60,
  DB_CONNECTION_TIMEOUT: 5000,
  DB_RECONNECT: true,
  DB_RECONNECT_INTERVAL: 1000,
  DB_RECONNECT_TRIES: 30,
  URLS: {
    PEOPLE_PROFILE_BATCH_ID_MAPPING_URL: '/idmappings/batch',
  },
  AUTHORIZATION: 's2s_auth_token',
  CONNECTIONS_OMIT_HEADERS: 'organizationId,name,emails,id,key,data',
};
